### ISSUE TITLE
Reuse Base() method in SlotBuffer()

### ISSUE THREAD

**Issue by delimitry** [pragus/gonetmap#3]
Maybe reuse `Base()`:
https://github.com/pragus/gonetmap/blob/74913bb288ca6d51b83f0a5523806d8cb12452a1/ring.go#L34-L37 here in `SlotBuffer()`:
https://github.com/pragus/gonetmap/blob/74913bb288ca6d51b83f0a5523806d8cb12452a1/ring.go#L67-L68

**Comment by pragus** [comment]
fixed in 2e35bbbc2697024ad7a68f226bd302b505480862
